services:
  - type: web
    name: aetherwood-studio
    runtime: python
    buildCommand: "python manage.py migrate"
    startCommand: "gunicorn aetherwood.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0